<?php

return [

    /*
    |--------------------------------------------------------------------------
    | User Defined Variables
    |--------------------------------------------------------------------------
    |
    | This is a set of variables that are made specific to this application
    | that are better placed here rather than in .env file.
    | Use config('your_key') to get the values.
    |
    */

    'currencies' => array(
        'LTC',
        'XVG',
        'NXS',
        'PTOY',
        'OMG',
        'ETH',
        'ETC',
        'NEO',
        'STRAT',
        'PAY',
        'ZEC',
        'QTUM',
        'SNT',
        'NXC',
        'LSK',
        'XMR',
        'DASH',
        'BAT',
        'MCO',
        'BCC',
        'WAVES',
        'RDD',
        'GAME',
        'ARK',
        'BAY',
        'TRUST',
        'EBST',
        'XRP',
        'ADX',
        'EDG',
        'NAV',
        'SC',
        'PIVX',
        'UBQ',
        'GNT',
        'COVAL'
    ),


    'currencies_arbitration' => array(
        "LTC",
        "NMC",
        "PPC",
        "DASH",
        "DOGE",
        "CANN",
        "VIA",
        "START",
        "VTC",
        "NAV",
        "SYS",
        "OK",
        "SPR",
        "GEO",
        "DGB",
        "XVG",
        "BITB",
        "CLAM",
        "NOTE",
        "RDD",
        "PKB",
        "SNRG",
        "IOC",
        "TX",
        "SIB",
        "INFX",
        "GCR",
        "EMC",
        "MUE",
        "EGC",
        "SLS",
        "NLG",
        "CPC",
        "PIVX",
        "CRW",
        "CLOAK",
        "CLUB",
        "DCR",
        "TKN",
        "2GIVE",
        "AUR",
        "SYNX",
        "ZEC",
        "GAME",
        "ABY",
        "XMG",
        "RBY",
        "BCC",
        "BAT",
        "GNT",
        "TIME",
        "GNO",
        "STORJ",
        "BNT",
        "ETH",
        "EXP",
        "LSK",
        "WAVES",
        "RISE",
        "ETC",
        "BTS",
        "HMQ",
        "MCO",
        "XEM",
    ),


];